version: '3'
services:
  playground:
    container_name: 'USPTO-RELEASE'
    hostname: 'python'
    build: .
    shm_size: '54gb'
    restart: always
    working_dir: '/kaggle'
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /kaggle
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]